Feature Parity with Irys Elapsed time
saplinganon/imissfauna.com pull request #2
Opened 2021-12-03 11:34 UTC by BlueDo

Re-implement the timer feature from Irys with React + npm approach

2021-12-03 23:03 UTC, saplinganon commented
Can you make the timer use the TextCountdown component instead? It doesn't depend on date-fns, but you will need to add support for singular time units.

I'd also like to make sure we have permission from @irystocratanon before copying the paststream API code.

2021-12-04 02:40 UTC, BlueDo commented
Will make the change. What do you mean by "singular time units"?
Also, can you add @irystocratanon to the watchlist? I don't think I have the ability to do that.

2021-12-04 04:07 UTC, saplinganon commented
I mean some code to distinguish between 1 second/N seconds cases in TextCountdown. Basically just check if the number is 1 and use an alternate format string if so.

Tagging irystocratanon should have sent a notification already, so don't worry about it. I'll probably just post in the IRyS thread later if they don't reply here.

2021-12-04 06:22 UTC, irystocratanon commented
You can copy any code from me. I don't mind.

2021-12-05 07:26 UTC, BlueDo commented
I have made revision. Please take a look. 
Decided to add Streamer Name to env and export to frontend. Intention is to move more things to config to make forking easier in the future.

2021-12-05 08:37 UTC, saplinganon requested changes

2021-12-05 08:37 UTC, saplinganon commented on server/paststream_poller.js
> +        return { error: e.toString(), result: { items: [] } }
Please make the result for the error case `null`, since it'll never be used by pollPaststreamStatus.

2021-12-05 08:37 UTC, saplinganon commented on server/paststream_poller.js
> +    return extractPaststreamInfo(youtubeJSON)
Please wrap this in a `{ error, result }` object to be consistent with the error case.

2021-12-05 08:37 UTC, saplinganon commented on components/text_countdown.js
> +        return this.formattedTime(components, isNegative)
Is there a reason for removing the wrapper tag here? (If you really mean to, please wrap this in a fragment.)

2021-12-05 08:37 UTC, saplinganon commented on pages/index.js
> +    pastStream = await pollPaststreamStatus(process.env.WATCH_CHANNEL_ID)
Following from my other comment on pollPaststreamStatus, we will need to do the same unpacking dance as pollLivestreamStatus here.

2021-12-05 08:37 UTC, saplinganon commented on components/text_countdown.js
> +    state = {
Please put the explicit constructor back here.

2021-12-05 08:45 UTC, saplinganon commented
General comments: functionally this LGTM except for the things in the past stream API that need straightening out. I requested a few style changes in TextCountdown so we can keep the project at a "just finished a react tutorial" level of complexity.

Unfortunately I'll have to reject the streamer name config as you've only changed one instance of it. Feel free to change the rest (or heck, just make all the strings localizable) and resubmit it in another PR, though.

2021-12-07 00:33 UTC, BlueDo commented
I have made another revision. 
If you do merge, please remember to squash before merging so that the history is cleaner.

2021-12-07 02:04 UTC, saplinganon commented
Looks great, thanks for the PR. Will merge in a bit.

2021-12-07 03:05 UTC, saplinganon commented
Merged in bad9d59.

2021-12-07 03:05 UTC, closed without merging