Clicking on the current image cycles to the next one (And new have-stream images)
saplinganon/imissfauna.com pull request #3
Opened 2021-12-16 08:50 UTC by tralezab

## What

Makes OnClick use `selectNextImage` instead of `selectRandomImage`, which as the name implies, selects the next image in the set instead of randomly choosing.

Adds love.png, and spential_love.png to the imageset for having a stream.

## Why

Without seeing duplicates you really get to enjoy the full gallery, and the have-stream imageset only had a single image when the quintessential sapling experience clearly dictates many mood swings

2021-12-16 10:03 UTC, saplinganon requested changes
Sounds like a good idea. However, I'd like the cycling order to be randomized as well if we're going to implement this.

I also want to restrict the I Don't Miss Fauna set to just normal images (thus implying that saplings only get weird when she's gone).

2021-12-16 11:01 UTC, tralezab commented
> Sounds like a good idea. However, I'd like the cycling order to be randomized as well if we're going to implement this.

Sure, should just be a shuffle after the imageset is randomized for the first time.

> I also want to restrict the I Don't Miss Fauna set to just normal images (thus implying that saplings only get weird when she's gone).

I like that idea a lot actually. Keeping love, removing the deformed version.

2021-12-16 11:03 UTC, tralezab commented on pages/index.js
> +    return fromSet[(((nextIndex - 0) % (fromSet.length - 0)) + 0)  | 0]
Er...  whoops! It's surprising how simple wrapping gets when your lower bound is zero. I should have paid more attention.

2021-12-16 21:05 UTC, tralezab commented
Alright tell me if I did anything bad with state there, from testing this works nicely for shuffling the imageset

2021-12-16 22:00 UTC, saplinganon requested changes

2021-12-17 23:17 UTC, merged

2021-12-17 23:28 UTC, saplinganon commented
Live now, thanks for the PR!